'use client';
import { FormEvent, useState } from 'react';
import AuthGuard from '@/components/AuthGuard';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import { currentUser, readJson, todayKey, writeJson } from '@/lib/storage';
const ideas=[['Bowl de pollo y verduras','520','44','12','Almuerzo'],['Omelette con espinaca y queso fresco','360','31','5','Desayuno'],['Yogur griego, berries y semillas','290','24','9','Snack'],['Salmón con ensalada tibia','540','42','10','Cena'],['Ensalada de atún y garbanzos','470','39','14','Almuerzo'],['Pavo con zapallo italiano salteado','410','46','8','Cena']];
export default function FoodPage(){return <AuthGuard userOnly><AppShell><Food/></AppShell></AuthGuard>}
function Food(){const user=currentUser()!;const key=`ritmo_food_${user.username}_${todayKey()}`;const [foods,setFoods]=useState<any[]>(()=>readJson(key,[]));const [name,setName]=useState('');const [cal,setCal]=useState('');const [pro,setPro]=useState('');const [fiber,setFiber]=useState('');
 function add(e:FormEvent){e.preventDefault();if(!name||!cal)return;const next=[...foods,{id:crypto.randomUUID(),name,calories:Number(cal),protein:Number(pro||0),fiber:Number(fiber||0)}];setFoods(next);writeJson(key,next);setName('');setCal('');setPro('');setFiber('')}
 const totals=foods.reduce((a,x)=>({cal:a.cal+x.calories,pro:a.pro+x.protein,fib:a.fib+x.fiber}),{cal:0,pro:0,fib:0});
 return <><PageHeader eyebrow="ALIMENTACIÓN" title="Registro de comidas" text="Lleva una referencia simple de calorías, proteína y fibra sin convertir cada comida en una planilla."/>
 <div className="macro-grid"><div><span>Calorías</span><b>{totals.cal.toLocaleString('es-CL')}</b><small>kcal hoy</small></div><div><span>Proteína</span><b>{Math.round(totals.pro)}</b><small>gramos</small></div><div><span>Fibra</span><b>{Math.round(totals.fib)}</b><small>gramos</small></div><div><span>Comidas</span><b>{foods.length}</b><small>registros</small></div></div>
 <div className="two-col"><section className="card"><h2>Agregar comida</h2><form className="compact-form" onSubmit={add}><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Pollo con ensalada"/></label><div className="split"><label>Calorías<input type="number" min="0" value={cal} onChange={e=>setCal(e.target.value)} placeholder="520"/></label><label>Proteína (g)<input type="number" min="0" value={pro} onChange={e=>setPro(e.target.value)} placeholder="Opcional"/></label></div><label>Fibra (g)<input type="number" min="0" value={fiber} onChange={e=>setFiber(e.target.value)} placeholder="Opcional"/></label><button className="primary">Guardar comida</button></form><div className="food-list">{foods.map((f,i)=><div key={f.id}><span>{i===0?'🍽️':'🥣'}</span><div><b>{f.name}</b><small>{f.calories} kcal · {f.protein||0} g proteína · {f.fiber||0} g fibra</small></div><button className="ghost danger" onClick={()=>{const n=foods.filter(x=>x.id!==f.id);setFoods(n);writeJson(key,n)}}>Eliminar</button></div>)}</div></section>
 <section className="card"><div className="row-between"><h2>Ideas nutritivas</h2><span className="pill">Alta proteína + fibra</span></div><div className="idea-list">{ideas.map(x=><div key={x[0]}><div className="idea-icon">🥗</div><div><b>{x[0]}</b><small>{x[4]}</small><p>{x[1]} kcal · <strong>{x[2]} g proteína</strong> · {x[3]} g fibra</p></div></div>)}</div></section></div>
 </>}
