'use client';
import { useState } from 'react';import AuthGuard from '@/components/AuthGuard';import AppShell from '@/components/AppShell';import PageHeader from '@/components/PageHeader';import { getUsers, saveUsers } from '@/lib/storage';
export default function AdminPage(){return <AuthGuard adminOnly><AppShell><Admin/></AppShell></AuthGuard>}
function Admin(){const [users,setUsers]=useState(()=>getUsers());function toggle(u:string){const n=users.map(x=>x.username===u?{...x,active:!x.active}:x);setUsers(n);saveUsers(n)}function role(u:string){const n=users.map(x=>x.username===u?{...x,role:(x.role==='admin'?'user':'admin') as 'user'|'admin'}:x);setUsers(n);saveUsers(n)}
 return <><PageHeader eyebrow="ADMINISTRACIÓN" title="Control general de la plataforma" text="Gestiona usuarios y deja preparada la aplicación para parámetros globales y bibliotecas compartidas."/>
 <div className="admin-kpis"><div><span>Usuarios</span><b>{users.length}</b></div><div><span>Activos</span><b>{users.filter(x=>x.active).length}</b></div><div><span>Administradores</span><b>{users.filter(x=>x.role==='admin').length}</b></div></div>
 <section className="card"><div className="row-between"><h2>Usuarios registrados</h2><span className="pill">MULTIUSUARIO</span></div><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map(u=><tr key={u.username}><td><b>{u.name}</b></td><td>{u.username}</td><td><span className="pill">{u.role}</span></td><td><span className={`status ${u.active?'ok':'off'}`}>{u.active?'Activo':'Suspendido'}</span></td><td><div className="actions"><button className="ghost" disabled={u.username==='Diego.123'} onClick={()=>role(u.username)}>Cambiar rol</button><button className="ghost danger" disabled={u.username==='Diego.123'} onClick={()=>toggle(u.username)}>{u.active?'Suspender':'Activar'}</button></div></td></tr>)}</tbody></table></div></section>
 <section className="admin-modules"><div className="card"><span>🏋️</span><h3>Biblioteca de ejercicios</h3><p>Base preparada para administrar ejercicios, técnica, series y descansos.</p><button className="ghost">Próxima etapa</button></div><div className="card"><span>🥗</span><h3>Biblioteca de comidas</h3><p>Base preparada para recetas, calorías, proteínas, fibra y categorías.</p><button className="ghost">Próxima etapa</button></div><div className="card"><span>⚙️</span><h3>Parámetros generales</h3><p>Metas sugeridas, mensajes, rangos y configuración global.</p><button className="ghost">Próxima etapa</button></div></section>
 </>}
