'use client';
import { FormEvent, useState } from 'react';
import AuthGuard from '@/components/AuthGuard';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import ProgressBar from '@/components/ProgressBar';
import { currentUser, readJson, todayKey, writeJson } from '@/lib/storage';

type Reading={id:string;title:string;type:string;totalPages:number;currentPage:number;completed:boolean};
export default function ReadingPage(){return <AuthGuard><AppShell><ReadingPanel/></AppShell></AuthGuard>}
function ReadingPanel(){
 const user=currentUser()!; const key=`ritmo_readings_${user.username}`; const [readings,setReadings]=useState<Reading[]>(()=>readJson(key,[]));
 const [title,setTitle]=useState(''); const [type,setType]=useState('Libro'); const [pages,setPages]=useState(''); const [selected,setSelected]=useState<string|null>(readings[0]?.id||null); const [current,setCurrent]=useState(''); const [summary,setSummary]=useState('');
 const book=readings.find(r=>r.id===selected);
 function add(e:FormEvent){e.preventDefault(); if(!title||!pages)return; const item={id:crypto.randomUUID(),title,type,totalPages:Number(pages),currentPage:0,completed:false}; const n=[item,...readings]; setReadings(n);writeJson(key,n);setSelected(item.id);setTitle('');setPages('')}
 function saveProgress(){if(!book||current==='')return; const requested=Number(current); if(!Number.isFinite(requested)||requested<book.currentPage)return; const nextPage=Math.min(requested,book.totalPages); const addedPages=Math.max(0,nextPage-book.currentPage); const logKey=`ritmo_readlog_${user.username}_${book.id}_${todayKey()}`; const previous=readJson<any>(logKey,{pages:0,page:book.currentPage,summary:'',date:todayKey()}); const next=readings.map(r=>r.id===book.id?{...r,currentPage:nextPage,completed:nextPage>=r.totalPages}:r); setReadings(next);writeJson(key,next);writeJson(logKey,{pages:Number(previous.pages||0)+addedPages,page:nextPage,summary:summary.trim()||previous.summary||'',date:todayKey()});setSummary('');setCurrent('')}
 return <><PageHeader eyebrow="LECTURA" title="Tu biblioteca personal" text="Avanza a tu ritmo y deja una pequeña síntesis de lo que te llevas cada día."/>
 <div className="two-col"><section className="card"><h2>Mis lecturas</h2><form className="compact-form" onSubmit={add}><input placeholder="Título de la lectura" value={title} onChange={e=>setTitle(e.target.value)}/><div className="split"><select value={type} onChange={e=>setType(e.target.value)}><option>Libro</option><option>Revista</option><option>PDF</option><option>Artículo</option><option>Otro</option></select><input type="number" min="1" placeholder="Páginas" value={pages} onChange={e=>setPages(e.target.value)}/></div><button className="primary">+ Agregar lectura</button></form>
 <div className="book-list">{readings.length===0&&<div className="empty">Aún no has agregado lecturas.</div>}{readings.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`book-item ${selected===r.id?'selected':''}`}><div className="book-cover">📖</div><div><b>{r.title}</b><span>{r.currentPage} / {r.totalPages} páginas</span><ProgressBar value={r.currentPage/r.totalPages*100}/></div><strong>{Math.round(r.currentPage/r.totalPages*100)}%</strong></button>)}</div></section>
 <section className="card">{book?<><span className="pill">LECTURA ACTIVA</span><h2>{book.title}</h2><div className="reading-big"><b>{Math.round(book.currentPage/book.totalPages*100)}%</b><span>{book.currentPage} de {book.totalPages} páginas</span></div><ProgressBar value={book.currentPage/book.totalPages*100}/><label>¿Hasta qué página llegaste hoy?<input type="number" min={book.currentPage} max={book.totalPages} value={current} onChange={e=>setCurrent(e.target.value)} placeholder={`Mínimo ${book.currentPage}`}/></label><label>¿Qué te dejó la lectura de hoy?<textarea maxLength={500} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Escribe una síntesis breve…"/><small className="counter">{summary.length}/500</small></label><button className="primary full" onClick={saveProgress}>Guardar avance de hoy</button></>:<div className="empty tall">Selecciona o agrega una lectura para comenzar.</div>}</section></div>
 </>}
