'use client';
import AuthGuard from '@/components/AuthGuard';import AppShell from '@/components/AppShell';import PageHeader from '@/components/PageHeader';import ProgressBar from '@/components/ProgressBar';import { currentUser, dateKey, getGoals, readJson } from '@/lib/storage';
export default function ProgressPage(){return <AuthGuard><AppShell><Progress/></AppShell></AuthGuard>}
function Progress(){const user=currentUser()!;const goals=getGoals(user.username);const readings=readJson<any[]>(`ritmo_readings_${user.username}`,[]);const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(6-i));return dateKey(d)});const rows=days.map(d=>{const ex=readJson<any>(`ritmo_exercise_${user.username}_${d}`,{completed:false}).completed;const sl=readJson<any>(`ritmo_sleep_${user.username}_${d}`,{hours:0}).hours||0;const wa=readJson<number>(`ritmo_water_${user.username}_${d}`,0);const fo=readJson<any[]>(`ritmo_food_${user.username}_${d}`,[]).length>0;const pages=readings.reduce((sum,r)=>sum+Number(readJson<any>(`ritmo_readlog_${user.username}_${r.id}_${d}`,{pages:0}).pages||0),0);const checks=[ex,pages>=goals.readingPages,sl>=goals.sleepHours,wa>=goals.hydrationMl,!goals.foodTracking||fo];return{d,score:checks.filter(Boolean).length/checks.length*100,ex,pages,sl,wa,fo}});const avg=Math.round(rows.reduce((s,x)=>s+x.score,0)/7);const exCount=rows.filter(x=>x.ex).length;const sleep=(rows.reduce((s,x)=>s+x.sl,0)/7).toFixed(1);const water=Math.round(rows.reduce((s,x)=>s+x.wa,0)/7);
 return <><PageHeader eyebrow="PROGRESO" title="Tu última semana" text="La tendencia importa más que un día aislado. Observa qué hábitos ya están tomando forma."/>
 <div className="macro-grid"><div><span>Cumplimiento</span><b>{avg}%</b><small>promedio semanal</small></div><div><span>Entrenamientos</span><b>{exCount}</b><small>últimos 7 días</small></div><div><span>Sueño</span><b>{sleep} h</b><small>promedio</small></div><div><span>Agua</span><b>{water} ml</b><small>promedio diario</small></div></div>
 <section className="card"><h2>Consistencia diaria</h2><div className="week-chart">{rows.map(r=><div key={r.d}><div className="bar-wrap"><span style={{height:`${Math.max(4,r.score)}%`}}/></div><b>{new Intl.DateTimeFormat('es-CL',{weekday:'short'}).format(new Date(r.d+'T12:00:00')).replace('.','')}</b><small>{Math.round(r.score)}%</small></div>)}</div></section>
 <section className="card"><h2>Resumen por hábito</h2><div className="summary-list"><Summary title="Ejercicio" value={exCount/7*100}/><Summary title="Lectura" value={rows.filter(x=>x.pages>=goals.readingPages).length/7*100}/><Summary title="Sueño" value={rows.filter(x=>x.sl>=goals.sleepHours).length/7*100}/><Summary title="Hidratación" value={rows.filter(x=>x.wa>=goals.hydrationMl).length/7*100}/><Summary title="Alimentación" value={rows.filter(x=>x.fo).length/7*100}/></div></section></>}
function Summary({title,value}:{title:string;value:number}){return <div><div className="row-between"><b>{title}</b><span>{Math.round(value)}%</span></div><ProgressBar value={value}/></div>}
